name: lohaghara_carrier
description: "A production-level logistics management app."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter 

  # State Management + Routing + Dl
  get: ^4.7.3 


  # Firebase
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0

  # Local Storage
  shared_preferences: ^2.5.5


  # Security
  local_auth: ^3.0.1 


  # Pdf & Printing
  pdf: ^3.12.0
  printing: ^5.14.3


  # Animations
  lottie: ^3.3.3


  # Date picker
  intl: ^0.20.2 
  month_picker_dialog: ^6.7.2


  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  flutter_svg: ^2.2.4 


  # Utilities 
  uuid: ^4.5.3
  equatable: ^2.0.8
  url_launcher: ^6.3.2
  smooth_page_indicator: ^2.0.1
  flutter_launcher_icons: ^0.14.4
  get_storage: ^2.1.1
  connectivity_plus: ^7.1.1
  shimmer: ^3.0.0
  firebase_storage: ^13.4.2
  google_sign_in: ^6.1.6



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 
  rename_app: ^1.6.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/app_icon.png"
  adaptive_icon_foreground: "assets/images/icons/app_icon_foreground.png"
  adaptive_icon_background: "assets/images/icons/app_icon_background.png"


flutter:

  uses-material-design: true

  #----------------Local Assets-----------------#
  assets:
    - assets/images/logos/
    - assets/images/onboarding/
    - assets/images/icons/
    - assets/images/user/
    - assets/animations/
  
  #-----------------LOCAL FONTS-----------------# 

  fonts:
    - family: Poppins 
      fonts:
        - asset: assets\fonts\poppins.light.ttf 
          weight: 300 
        - asset: assets\fonts\poppins.regular.ttf 
          weight: 400 
        - asset: assets\fonts\poppins.italic.ttf 
          style: italic 
        - asset: assets\fonts\poppins.medium.ttf 
          weight: 500
        - asset: assets\fonts\poppins.medium-italic.ttf 
          weight: 500 
          style: italic 
        - asset: assets\fonts\poppins.semibold.ttf 
          weight: 600
        - asset: assets\fonts\poppins.bold.ttf 
          weight: 800
